### ISSUE TITLE
git: «desc» not command git. View «git --help»

### ISSUE THREAD

**Issue by akaguny** [seebi/zshrc#6]
when i go to dir where i has init git, i see these message

**Comment by tylercrompton** [comment]
I replaced the contents of the command substitution in [line 40 of prompt.zsh] with the the contents of [git-desc from Quilt](http://git.savannah.gnu.org/cgit/quilt.git/plain/git-desc) (without the shebang).

**Comment by seebi** [comment]
oh sorry. This refers to my gitconfig 
https://github.com/seebi/rc/blob/master/rc/gitconfig#L28

**Comment by tylercrompton** [comment]
Maybe update the aforementioned line to not depend on that repository?

**Comment by sourav26721062** [comment]
<img width="1440" alt="screen shot 2016-07-30 at 5 52 19 pm" src="https://cloud.githubusercontent.com/assets/4952640/17270357/6409a396-567e-11e6-8a9f-288adb9eb466.png">

Hi what is the resolution ? 
I am facing the same issue

**Comment by seebi** [comment]
ok, fixed this
